databases:
  - name: flight-booker
    databaseName: flight-booker
    user: flight-booker

services:
  - type: web
    name: flight-booker
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flight-booker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false